config/routes.rb
Rails.application.routes.draw do
  devise_for :authors
  root to: 'blog/posts#index'

  # /author/posts/
  namespace :authors do
    get '/account' => 'accounts#edit', as: :account
    put '/info' => 'accounts#update_info', as: :info
    put '/change_password' => 'accounts#change_password', as: :change_password
    resources :posts do
      put 'publish' => 'posts#publish', on: :member
      put 'unpublish' => 'posts#unpublish', on: :member
    end
  end
  
  # /
  # /posts
  scope module: 'blog' do
    get 'about' => 'pages#about', as: :about
    get 'contact' => 'pages#contact', as: :contact  
    get 'posts' => 'posts#index', as: :posts
    get 'posts/:id' => 'posts#show', as: :post

    # 'posts/jimbob' => params[:id] == 'jimbob'

  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/post.rb
# == Schema Information
#
# Table name: posts
#
#  id               :integer          not null, primary key
#  title            :string
#  body             :text
#  description      :text
#  slug             :string
#  created_at       :datetime         not null
#  updated_at       :datetime         not null
#  banner_image_url :string
#  author_id        :integer
#  published        :boolean          default(FALSE)
#  published_at     :datetime
#
# Indexes
#
#  index_posts_on_author_id  (author_id)
#  index_posts_on_slug       (slug) UNIQUE
#

class Post < ApplicationRecord

    acts_as_taggable_on :tags# Alias for acts_as_taggable_on :tags    
    
    extend FriendlyId
    friendly_id :title, use: :slugged

    belongs_to :author, :optional => true

    PER_PAGE = 3

    scope :most_recent, -> { order(published_at: :desc) }
    scope :published, -> { where(published: true) }
    scope :recent_paginated, -> (page) { most_recent.paginate(page: page, per_page: PER_PAGE) }
    scope :with_tag, -> (tag) { tagged_with(tag) if tag.present? }
    
    scope :list_for, -> (page, tag) do
       # tag.present? ? recent_paginated(page).tagged_with(tag) : recent_paginated(page)
        recent_paginated(page).with_tag(tag)             
    end


    def should_generate_new_friendly_id?
        title_changed?
    end

    def display_day_published
        if published_at.present?
            "Published #{published_at.strftime('%-b %-d, %Y')}"
        else
            "Not published yet."
        end
    end

    def publish
        update(published: true, published_at: Time.now)
    end

    def unpublish
        update(published: false, published_at: nil)
    end

end

app/controllers/authors/posts_controller.rb
module Authors
    class PostsController < AuthorController
        before_action :set_post, only: [:show, :edit, :update, :destroy, :publish, :unpublish]
      
        # GET /posts
        # GET /posts.json
        def index
          @posts = current_author.posts.most_recent
        end
      
        # GET /posts/1
        # GET /posts/1.json
        def show
        end
      
        # GET /posts/new
        def new
          @post = current_author.posts.new
        end
      
        # GET /posts/1/edit
        def edit
        end

        def publish
          @post.publish
          redirect_to authors_posts_url
        end

        def unpublish
          @post.unpublish
          redirect_to authors_posts_url
        end
      
        # POST /posts
        # POST /posts.json
        def create
          @post = current_author.posts.new(post_params)
      
          respond_to do |format|
            if @post.save
              format.html { redirect_to authors_post_path(@post), notice: 'Post was successfully created.' }
              format.json { render :show, status: :created, location: @post }
            else
              format.html { render :new }
              format.json { render json: @post.errors, status: :unprocessable_entity }
            end
          end
        end
      
        # PATCH/PUT /posts/1
        # PATCH/PUT /posts/1.json
        def update
          respond_to do |format|
            if @post.update(post_params)
              format.html { redirect_to authors_post_path(@post), notice: 'Post was successfully updated.' }
              format.json { render :show, status: :ok, location: @post }
            else
              format.html { render :edit }
              format.json { render json: @post.errors, status: :unprocessable_entity }
            end
          end
        end
      
        # DELETE /posts/1
        # DELETE /posts/1.json
        def destroy
          @post.destroy
          respond_to do |format|
            format.html { redirect_to authors_posts_url, notice: 'Post was successfully destroyed.' }
            format.json { head :no_content }
          end
        end
      
        private
          # Use callbacks to share common setup or constraints between actions.
          def set_post
            @post = current_author.posts.friendly.find(params[:id])
          end
      
          # Never trust parameters from the scary internet, only allow the white list through.
          def post_params
            params.require(:post).permit(:title, :body, :description, :banner_image_url, :tag_list)
          end
      end  
end

app/controllers/blog/pages_controller.rb
module Blog
    class PagesController < BlogController
        def about
            
        end
    
        def contact
            
        end
    end
end

app/controllers/blog/posts_controller.rb
module Blog
    class PostsController < BlogController
      
        # GET /posts
        # GET /posts.json
        def index
            @posts = storage.list_for(params[:page], params[:tag])
        end
      
        # GET /posts/1
        # GET /posts/1.json
        def show
          @post = storage.friendly.find(params[:id])
        end

        private
        
        def storage
            Post.published
        end

      end  
end

app/controllers/blog_controller.rb
class BlogController < ApplicationController
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/blog/posts/_post.html.erb
<div class='col-sm-6 col-lg-4'>
    <div class="card">
        <%= link_to post do %>
            <div class="card-topper" style='background-image: url("<%= post.banner_image_url %>");'></div>
        <% end %>
        <div class="card-block">
            <h4 class="card-title"><%= link_to post.title, post %></h4>
            <p class='tags'><%= raw post.tags.map { |t| link_to t.name, posts_path(tag: t.name) }.join(', ') %></p>
            <h6 class="published-date"><%= post.display_day_published %></h6>
            <%= link_to post do %>
                <p class="card-text"><%= truncate(post.description, length: 130, 
                    :escape => false).html_safe %></p>
            <% end %>
        </div>
    </div>
</div>

app/views/blog/posts/index.html.erb
<% provide(:page_title, 'All Posts') %>
<% provide(:blog_active, 'active') %>

<div class="row">
  <%= render @posts %>
</div>
<div class="pagination apple_pagination">
  <%= will_paginate @posts %>    
</div>

app/views/blog/posts/show.html.erb
<% provide(:page_title, @post.title) %>
<% provide(:blog_active, 'active') %>

<div class="row">
  <div class="col-md-10 offset-md-1 col-lg-8 offset-lg-2 text-center">
    <h1><%= @post.title %></h1>
    <h6><%= @post.display_day_published %></h6>
    <%= @post.body.html_safe %>

    <div class="author-bio">
      <%= image_tag(@post.author.gravatar_image_url) %>
      <h4><%= @post.author.name %></h4>
      <h6 class="bio"><%= @post.author.bio %></h6>
    </div>

    <div id="disqus_thread"></div>

  </div>
</div>

<script>
  
  var disqus_config = function () {
    this.page.url = '<%= request.original_url %>';  // Replace PAGE_URL with your page's canonical URL variable
    this.page.identifier = '<%= @post.slug %>'; // Replace PAGE_IDENTIFIER with your page's unique identifier variable
  };
  

  (function() { // DON'T EDIT BELOW THIS LINE
  var d = document, s = d.createElement('script');
  s.src = 'https://my-blog-yo2wq7dikr.disqus.com/embed.js';
  s.setAttribute('data-timestamp', +new Date());
  (d.head || d.body).appendChild(s);
  })();
</script>
  <noscript>
    Please enable JavaScript to view the <a href="https://disqus.com/?ref_noscript">comments powered by Disqus.</a>
  </noscript>