config/routes.rb
Rails.application.routes.draw do
  devise_for :authors
  root to: 'blog/posts#index'

  # /author/posts/
  namespace :authors do
    get '/account' => 'accounts#edit', as: :account
    put '/info' => 'accounts#update_info', as: :info
    put '/change_password' => 'accounts#change_password', as: :change_password
    resources :posts do
      put 'publish' => 'posts#publish', on: :member
      put 'unpublish' => 'posts#unpublish', on: :member
    end
  end
  
  # /
  # /posts
  scope module: 'blog' do
    get 'about' => 'pages#about', as: :about
    get 'contact' => 'pages#contact', as: :contact  
    get 'posts' => 'posts#index', as: :posts
    get 'posts/:id' => 'posts#show', as: :post

    # 'posts/jimbob' => params[:id] == 'jimbob'

  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light sticky-top">
  <div class="container">
    <a class="navbar-brand" href="/">
      <%= image_tag("boy.png", :alt => "logo", :class=>"d-inline-block align-top logo-img") %> 
      My<span class="light <%= yield(:blog_active) %>">blog</span>
    </a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
      
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav ml-auto">
        <li class="nav-item">
          <%= link_to  "Blog", root_path, class: "nav-link #{yield(:blog_active)}" %>
        </li>
        <li class="nav-item">
          <%= link_to  "About", about_path, class: "nav-link #{yield(:about_active)}" %>
        </li>
        <li class="nav-item">
            <%= link_to  "Contact", contact_path, class: "nav-link #{yield(:contact_active)}" %>
        </li>
        <% if author_signed_in? %>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle author-nav <%= yield(:author) %>" href="#" id="navbarDropdownMenuLink" role="button"
              data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              <%= image_tag(current_author.gravatar_image_url) %>
              <%= current_author.display_name %>
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
              <%= link_to  'My posts', authors_posts_path, class: "dropdown-item" %>
              <%= link_to  'Account', authors_account_path, class: "dropdown-item" %>
              <%= link_to  'Logout', destroy_author_session_path, method: :delete, class: "dropdown-item" %>
            </div>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title> <%= yield(:page_title) %> | MyBlog</title>
    <%= favicon_link_tag asset_path('boy.png'), :rel => 'icon', :type =>  'image/png' %>    
    <%= csrf_meta_tags %>
    <link href="https://fonts.googleapis.com/css?family=Merriweather:400,400i,700|Montserrat:300,400,700" rel="stylesheet">    
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>    
    
  </head>

  <body>
    <%= render  "layouts/navbar" %>
    <div class="container <%= controller_name %> <%= action_name %>">
      <%= yield %>
    </div>
  </body>
</html>

app/views/layouts/author.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title> <%= yield(:page_title) %> | MyBlog</title>
    <%= favicon_link_tag asset_path('boy.png'), :rel => 'icon', :type =>  'image/png' %>    
    <%= csrf_meta_tags %>
    <link href="https://fonts.googleapis.com/css?family=Merriweather:400,400i,700|Montserrat:300,400,700" rel="stylesheet">    
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>    
    
  </head>

  <body>
    <%= render  "layouts/navbar" %>
    <div class="container <%= controller_name %> <%= action_name %>">
      <%= yield %>
    </div>
  </body>
</html>